version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '07:00'
      timezone: 'America/Recife'
    labels:
      - github_actions

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '07:00'
      timezone: 'America/Recife'
    rebase-strategy: 'disabled'
    open-pull-requests-limit: 10
    labels:
      - dependencies
